export CUDA_VISIBLE_DEVICES=0

model_name=AdaWaveNet

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./data/electricity/ \
  --data_path electricity.csv \
  --model_id ECL_96_96 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --d_model 256\
  --d_ff 256\
  --batch_size 16\
  --learning_rate 0.0005\
  --itr 1\
  --lifting_levels 3\
  --lifting_kernel_size 7\
  --n_clusters=4

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./data/electricity/ \
  --data_path electricity.csv \
  --model_id ECL_192_192 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 192 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --d_model 256\
  --d_ff 256\
  --batch_size 16\
  --learning_rate 0.0005\
  --itr 1\
  --lifting_levels 3\
  --lifting_kernel_size 7\
  --n_clusters=4

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./data/electricity/ \
  --data_path electricity.csv \
  --model_id ECL_336_336 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 336 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --d_model 256\
  --d_ff 256\
  --batch_size 16\
  --learning_rate 0.0005\
  --itr 1\
  --lifting_levels 3\
  --lifting_kernel_size 7\
  --n_clusters=4

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./data/electricity/ \
  --data_path electricity.csv \
  --model_id ECL_720_720 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 720 \
  --label_len 48 \
  --pred_len 720 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --d_model 256\
  --d_ff 256\
  --batch_size 16\
  --learning_rate 0.0005\
  --itr 1\
  --lifting_levels 3\
  --lifting_kernel_size 7\
  --n_clusters=4